### ISSUE TITLE
Invisible characters

### ISSUE THREAD

**Issue by kzsfluxus** [outboxcraft/beauter#15]
### Short Description

Invisible characters in input field. Maybe white characters in white input field.

### Platform

Beauter 3
Firefox 61.01, dark theme. Ubuntu 18.04 LTS

**Comment by ramdeoshubham** [comment]
That might be because of coloring classes overriding.
Can you please post an example code where this issue is happening?

**Comment by kzsfluxus** [comment]
I changed my Xubuntu global theme from Adwaita dark to Greybird, and now everything works fine.  When i used Adwaita there was problems with a lot of sites (eg. Facebook). So this was Adwaita related problem.

**Comment by ramdeoshubham** [comment]
So I guess it was not a beauter related issue.
XFCE might have been overriding some of the browser defaults values which were causing it.
Thank you very much @kzsfluxus to let us know about this.
I am closing this issue as its already resolved :)
