### ISSUE TITLE
Error/Typos in Docs

### ISSUE THREAD

**Issue by ErikThiart** [outboxcraft/beauter#16]
There are some mistakes in the docs on the website, is the website on github, then I can fix it.

**Comment by ramdeoshubham** [comment]
Yes, It is! It will be so great of you if you can contribute. 
Its here:  https://github.com/outboxcraft/beauter/tree/gh-pages

Thank you so much! 😄

**Comment by ramdeoshubham** [comment]
Where can I contact you personally? I have some stuff to tell which are under development so... you might ot need to bother much.

**Comment by ErikThiart** [comment]
You can find my email on here (https://erikthiart.com/contact.php) -- just don't want to put my email in the open for spiders to catch. 

On that page you see it is web@mydomain, just make it me@mydomain then it goes to my phone and PC.
