### ISSUE TITLE
Menubar?

### ISSUE THREAD

**Issue by Allen-B1** [outboxcraft/beauter#8]
Are there any menubars?

**Comment by Allen-B1** [comment]
Oh, there's `.topbar` but could you add documentation?

**Comment by Allen-B1** [comment]
Oh nevermind

**Comment by ramdeoshubham** [comment]
Hello Allen-B1,
I hope you have found what you are looking for is actually .topnav class explained here http://beauter.outboxcraft.com/docs/navigation/ 
There is no .topbar class available, any suggestion is welcomed :)

**Comment by Allen-B1** [comment]
Ok, thanks!
