### ISSUE TITLE
Not correct on Galaxy S8 / Chrome

### ISSUE THREAD

**Issue by christophe-mota** [outboxcraft/beauter#9]

**Comment by ramdeoshubham** [comment]
Hello,
Can you please explain the issue in brief? So that we can work on that in the upcoming update.
Thanks for letting us know of a issue :)

**Comment by christophe-mota** [comment]
Hi, my mistake I think... I just forgot to put in the html header :

meta name="viewport" content="width=device-width, initial-scale=1"

It worked fine in Firefox focus (mobile) but not in Chrome (mobile).
Thanks for Beauter, it's lightweight and usefull :)

**Comment by ramdeoshubham** [comment]
Welcome @christophe-mota :) 
Actually, we need to tell the browser to consider the device's width as webpage view width so that it can act responsive.
Please feel free to share your suggestions to improve Beauter.
